from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, ConfigDict, StringConstraints
from pydantic.types import JsonValue
from sqlmodel import Session

from noviscope.api.dependencies import get_session
from noviscope.api.routes import StageCardResponse, stage_response
from noviscope.auth.dependencies import get_current_user
from noviscope.core.json_types import JsonObject
from noviscope.core.stage_policy import IDEA_GENERATOR_AGENT_ID
from noviscope.models.quest import StageCard, StageStatus
from noviscope.models.user import User
from noviscope.quests.service import QuestService

router = APIRouter()

NonEmptyStr = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]


class IdeaSelectionError(Exception):
    def __init__(self, detail: str) -> None:
        self.detail = detail
        super().__init__(detail)


class IdeaSelectionRequest(BaseModel):
    model_config = ConfigDict(frozen=True)

    selected_idea_ids: list[NonEmptyStr]
    review_notes: str = ""


@router.post("/stages/{stage_id}/select-ideas", response_model=StageCardResponse)
def select_stage_ideas(
    stage_id: str,
    request: IdeaSelectionRequest,
    session: Annotated[Session, Depends(get_session)],
    current_user: Annotated[User, Depends(get_current_user)],
) -> StageCardResponse:
    service = QuestService(session)
    try:
        stage = service.get_stage_card_for_user(stage_id, current_user)
        selected_ideas = select_ideas(stage, request.selected_idea_ids)
        selected_idea_ids = [idea["idea_id"] for idea in selected_ideas]
        updated_stage = service.update_stage_card(
            stage_id,
            evidence_payload={
                **stage.evidence_payload,
                "human_selected_idea_ids": selected_idea_ids,
                "idea_selection_reviewed": True,
                "selected_idea_count": len(selected_ideas),
            },
            human_approved=True,
            human_approved_set=True,
            output_payload={
                **stage.output_payload,
                "selected_idea_ids": selected_idea_ids,
                "selected_ideas": selected_ideas,
                "selection_status": "selected_for_experiment_design",
            },
            review_notes=request.review_notes,
            summary=f"Selected {len(selected_ideas)} idea(s) for Experiment Planner.",
        )
        return stage_response(updated_stage)
    except LookupError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc
    except PermissionError as exc:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail=str(exc)) from exc
    except IdeaSelectionError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=exc.detail,
        ) from exc


def select_ideas(stage: StageCard, selected_idea_ids: list[str]) -> list[JsonObject]:
    ensure_selectable_idea_stage(stage)
    selected_ids = unique_selected_ids(selected_idea_ids)
    ideas = idea_payloads(stage.output_payload)
    ideas_by_id = {idea["idea_id"]: idea for idea in ideas}
    if not selected_ids:
        raise IdeaSelectionError("Select at least one generated idea.")
    if any(idea_id not in ideas_by_id for idea_id in selected_ids):
        raise IdeaSelectionError("Selected idea ids were not generated by this stage.")
    return [ideas_by_id[idea_id] for idea_id in selected_ids]


def ensure_selectable_idea_stage(stage: StageCard) -> None:
    if stage.agent_id != IDEA_GENERATOR_AGENT_ID:
        raise IdeaSelectionError(
            "Idea selection is only available for Gap & hypothesis generator stages."
        )
    if stage.status != StageStatus.COMPLETE:
        raise IdeaSelectionError("Gap & hypothesis generator must complete before selecting ideas.")


def unique_selected_ids(selected_idea_ids: list[str]) -> list[str]:
    selected_ids: list[str] = []
    seen: set[str] = set()
    for idea_id in selected_idea_ids:
        if idea_id in seen:
            continue
        seen.add(idea_id)
        selected_ids.append(idea_id)
    return selected_ids


def idea_payloads(output_payload: JsonObject) -> list[JsonObject]:
    ideas_value = output_payload.get("ideas")
    if not isinstance(ideas_value, list):
        return []
    ideas: list[JsonObject] = []
    for idea_value in ideas_value:
        if not isinstance(idea_value, dict):
            continue
        idea = idea_payload(idea_value)
        if idea is not None:
            ideas.append(idea)
    return ideas


def idea_payload(idea_value: dict[str, JsonValue]) -> JsonObject | None:
    idea_id = idea_value.get("idea_id")
    if not isinstance(idea_id, str) or not idea_id:
        return None
    return dict(idea_value)
